# Generated by Django 5.0.7 on 2024-07-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cold Beverages'), (2, 'Hot Beverages'), (3, 'Breakfast'), (4, 'Lunch'), (5, 'Snacks')]),
        ),
    ]
